### ISSUE TITLE
How to add a new repository?

### ISSUE THREAD

**Issue by CedsTrash** [itiden/statamic-backup#34]
Hi,

I was wondering how I could create another repository just like the build-in `FileBackupRepository`?
I need to customize the zipped filename for example.

I saw that you're binding the contract with the actual repo in your `ServiceProvider`, but how can I change that so it points to my custom repository without changing your code?

Thanks.

**Comment by NeoIsRecursive** [comment]
Right now I think it isn't possible, but it should definitely be an option in the configuration file.

**Comment by CedsTrash** [comment]
Yeah I understand your point.

At the moment I just need the $timestamp to be in a more human-redable format ('YYYY-MM-DD'), but I will also probably need to customize the entire name. My backups are part of a deployment process from an environment to another, so I need to name them like `$appName-$when-$environment---$datetime.zip`.

Example: `myApp-beforeDeploy-production---2024-06-14.zip`.

**Comment by NeoIsRecursive** [comment]
Ah I see, thanks!

Well, we've added a `repository` key to the config that makes it possible to bind other repositories, it will be in the next release (0.4.0).
